//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EnterLiveRoomMsg.proto
// Note: requires additional types generated from: UserData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterLiveRoomReq")]
  public partial class EnterLiveRoomReq : global::ProtoBuf.IExtensible
  {
    public EnterLiveRoomReq() {}
    
    private string _liveId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"liveId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string liveId
    {
      get { return _liveId; }
      set { _liveId = value; }
    }
    private string _userId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterLiveRoomRsp")]
  public partial class EnterLiveRoomRsp : global::ProtoBuf.IExtensible
  {
    public EnterLiveRoomRsp() {}
    
    private protocol.EnterLiveRoomRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.EnterLiveRoomRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.UserItem> _users = new global::System.Collections.Generic.List<protocol.UserItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.UserItem> users
    {
      get { return _users; }
    }
  
    private string _resultMessage = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"resultMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultMessage
    {
      get { return _resultMessage; }
      set { _resultMessage = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NO_AUTHORITY", Value=2)]
      NO_AUTHORITY = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnterLiveRoomSync")]
  public partial class EnterLiveRoomSync : global::ProtoBuf.IExtensible
  {
    public EnterLiveRoomSync() {}
    
    private readonly global::System.Collections.Generic.List<protocol.UserItem> _users = new global::System.Collections.Generic.List<protocol.UserItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.UserItem> users
    {
      get { return _users; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}