//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: test.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"addNumber")]
  public partial class addNumber : global::ProtoBuf.IExtensible
  {
    public addNumber() {}
    
    private int _number1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number1
    {
      get { return _number1; }
      set { _number1 = value; }
    }
    private int _number2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"number2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number2
    {
      get { return _number2; }
      set { _number2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestReq")]
  public partial class TestReq : global::ProtoBuf.IExtensible
  {
    public TestReq() {}
    
    private string _string1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"string1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string string1
    {
      get { return _string1; }
      set { _string1 = value; }
    }
    private string _string2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"string2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string string2
    {
      get { return _string2; }
      set { _string2 = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.addNumber> _numbers = new global::System.Collections.Generic.List<protocol.addNumber>();
    [global::ProtoBuf.ProtoMember(3, Name=@"numbers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.addNumber> numbers
    {
      get { return _numbers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TestRsp")]
  public partial class TestRsp : global::ProtoBuf.IExtensible
  {
    public TestRsp() {}
    
    private string _resultString;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string resultString
    {
      get { return _resultString; }
      set { _resultString = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.addNumber> _aaaa = new global::System.Collections.Generic.List<protocol.addNumber>();
    [global::ProtoBuf.ProtoMember(2, Name=@"aaaa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.addNumber> aaaa
    {
      get { return _aaaa; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"abc")]
  public partial class abc : global::ProtoBuf.IExtensible
  {
    public abc() {}
    
    private string _a;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string a
    {
      get { return _a; }
      set { _a = value; }
    }
    private int _b;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int b
    {
      get { return _b; }
      set { _b = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}