//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoHead.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ENetworkMessage")]
    public enum ENetworkMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"KEEP_ALIVE_SYNC", Value=0)]
      KEEP_ALIVE_SYNC = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFFLINE_SYNC", Value=1)]
      OFFLINE_SYNC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_LIVE_HALL_REQ", Value=100)]
      ENTER_LIVE_HALL_REQ = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_LIVE_HALL_RSP", Value=101)]
      ENTER_LIVE_HALL_RSP = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_LIVE_HALL_REQ", Value=102)]
      EXIT_LIVE_HALL_REQ = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_LIVE_HALL_RSP", Value=103)]
      EXIT_LIVE_HALL_RSP = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_LIVE_ROOM_REQ", Value=104)]
      ENTER_LIVE_ROOM_REQ = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_LIVE_ROOM_RSP", Value=105)]
      ENTER_LIVE_ROOM_RSP = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_LIVE_ROOM_SYNC", Value=106)]
      ENTER_LIVE_ROOM_SYNC = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_LIVE_ROOM_REQ", Value=107)]
      EXIT_LIVE_ROOM_REQ = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_LIVE_ROOM_RSP", Value=108)]
      EXIT_LIVE_ROOM_RSP = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXIT_LIVE_ROOM_SYNC", Value=109)]
      EXIT_LIVE_ROOM_SYNC = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_POSITION_REQ", Value=110)]
      MOVE_POSITION_REQ = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_POSITION_RSP", Value=111)]
      MOVE_POSITION_RSP = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_POSITION_SYNC", Value=112)]
      MOVE_POSITION_SYNC = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TALKING_REQ", Value=113)]
      TALKING_REQ = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TALKING_RSP", Value=114)]
      TALKING_RSP = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TALKING_SYNC", Value=115)]
      TALKING_SYNC = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_CHAT_REQ", Value=116)]
      SEND_CHAT_REQ = 116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SEND_CHAT_RSP", Value=117)]
      SEND_CHAT_RSP = 117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RECEIVE_CHAT_SYNC", Value=118)]
      RECEIVE_CHAT_SYNC = 118
    }
  
}