//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: TalkingMsg.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalkingReq")]
  public partial class TalkingReq : global::ProtoBuf.IExtensible
  {
    public TalkingReq() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private protocol.TalkingState _talking;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"talking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.TalkingState talking
    {
      get { return _talking; }
      set { _talking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalkingRsp")]
  public partial class TalkingRsp : global::ProtoBuf.IExtensible
  {
    public TalkingRsp() {}
    
    private protocol.TalkingRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.TalkingRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private string _resultMessage = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resultMessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string resultMessage
    {
      get { return _resultMessage; }
      set { _resultMessage = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TalkingSync")]
  public partial class TalkingSync : global::ProtoBuf.IExtensible
  {
    public TalkingSync() {}
    
    private string _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private protocol.TalkingState _talking;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"talking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.TalkingState talking
    {
      get { return _talking; }
      set { _talking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TalkingState")]
    public enum TalkingState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OFF", Value=0)]
      OFF = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ON", Value=1)]
      ON = 1
    }
  
}